FROM golang:1.13.8
ENV DAPPER_SOURCE /go/src/github.com/darkowlzz/storage-conformance-test-setup
ENV DAPPER_OUTPUT bin
ENV	DAPPER_DOCKER_SOCKET true
WORKDIR ${DAPPER_SOURCE}
RUN apt-get update && apt-get install rsync -y
ENTRYPOINT ["make", "binaries"]
