version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
    environment:
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    steps:
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - run:
          name: Create binaries
          command: |
            make binaries;
            cp -r bin ${TEST_RESULTS}
      # - run:
      #     name: Build kind images
      #     command: make images
      - store_artifacts:
          path: /tmp/test-results
